import re

with open('/Users/nguyetpham/Desktop/WEBSITE/writing-essays-b1level/app.js', 'r') as f:
    content = f.read()

# 1. Update TYPE 01 (adv-disadv) Dàn ý 02
old_adv_disadv_2 = """                <h4 style="color: var(--primary-color); margin-top: 25px;">BÀI MẪU 2: ÁP DỤNG DÀN Ý 02 (CHỈ THUẬN LỢI)</h4>
                <div class="sample-letter-box">
                    In recent years, <strong>online learning</strong> has become more common in modern society. Many people see this as a positive development. <strong>This essay will discuss the main advantages of this topic.</strong><br><br>
                    One main advantage is that <strong>it is convenient and flexible</strong>. <em>This is because learners can study anytime and anywhere, so they can manage their time better and balance learning with other activities.</em> Another positive aspect is that <strong>it helps save money</strong>. <em>The main reason is that students do not need to pay for transport, accommodation, or printed materials, so it is suitable for people with a limited budget.</em> A further benefit is that <strong>it allows learners to study at their own pace</strong>. <em>This means that they can review lessons many times if they do not understand, so they do not feel left behind.</em><br><br>
                    In conclusion, <strong>online learning</strong> offers several benefits. These advantages make it useful for many people. Overall, it is a positive development in modern society.
                </div>"""

new_adv_disadv_2 = """                <h4 style="color: var(--primary-color); margin-top: 25px;">BÀI MẪU 2: ÁP DỤNG DÀN Ý 02 (CHỈ THUẬN LỢI)</h4>
                <div class="sample-letter-box">
                    In recent years, <strong>doing volunteer work</strong> has become more common in modern society. Many people see this as a positive development. <strong>This essay will discuss the main advantages of this topic.</strong><br><br>
                    One main advantage is that <strong>volunteer work helps people develop important skills</strong>. <em>This is because volunteers communicate with many different people, so they can improve their communication skills. In addition, they work with others in different activities, so they can improve their teamwork skills and learn how to cooperate more effectively. As a result, they become more confident and gain useful experience for future jobs and studies.</em><br><br>
                    Another positive aspect is that <strong>participating in volunteer work brings benefits to the community</strong>. <em>The main reason is that volunteers help people in need, so some people can have better living conditions and receive more support. Moreover, volunteers can clean public areas or plant trees, so the environment can become cleaner and healthier. Therefore, some social and environmental problems can be reduced, and the community can become more connected.</em><br><br>
                    A further benefit is that <strong>doing voluntary activities helps people feel happier and more meaningful</strong>. <em>In fact, volunteers can help other people and do useful things for society, so they often feel proud of themselves. Besides, many volunteers receive appreciation from other people, so they feel more motivated to continue helping others. Consequently, they usually develop a more positive attitude toward life and care more about the people around them.</em><br><br>
                    In conclusion, <strong>volunteer work</strong> offers several benefits. These advantages make it useful for many people. Overall, it is a positive development in modern society.
                </div>"""

content = content.replace(old_adv_disadv_2, new_adv_disadv_2)

# 2. Update TYPE 02 (cause-effect) Dàn ý 02, 03, 04, 05, 06

# First, extract the entire cause-effect sampleWriting block from app.js
# and replace the specific sections.
# To make it safe, I'll use regex or replace specific blocks.

old_cause_effect_2 = """                <h4 style="color: var(--primary-color); margin-top: 25px;">BÀI MẪU 2: DÀN Ý 02 (NGUYÊN NHÂN & ẢNH HƯỞNG)</h4>
                <div class="sample-letter-box">
                    In recent years, <strong>obesity among young people</strong> has become a growing concern in many parts of the world. This issue affects both individuals and society in different ways. <strong>This essay will discuss the main causes of this problem and its possible effects.</strong><br><br>
                    <strong>This issue can be caused by several factors.</strong> One major cause is that <strong>many young people have unhealthy eating habits</strong>. <em>This is because they often eat fast food and drink sugary beverages, so they consume too much fat and sugar every day.</em> Another contributing factor is that <strong>many young individuals do not exercise regularly</strong>. <em>As a result, they do not burn enough calories and may gain weight easily.</em> A further reason is that <strong>many teenagers lack nutritional knowledge</strong>. <em>Consequently, they may choose unhealthy food and develop poor eating habits.</em><br><br>
                    <strong>This problem can lead to several negative effects.</strong> One serious impact is that <strong>it causes physical health problems</strong>. <em>For instance, overweight young people have a higher risk of heart disease and diabetes.</em> Another consequence is that <strong>it affects mental health negatively</strong>. <em>This is because obese teenagers often feel unconfident about their appearance and may suffer from depression.</em> A further problem is that <strong>it creates a burden on the healthcare system</strong>. <em>This means hospitals need to spend more resources treating obesity-related diseases.</em><br><br>
                    In conclusion, <strong>obesity among young people</strong> is caused by several factors and can lead to many negative effects. By understanding the causes and paying more attention to this issue, the situation can be improved in the future. These actions can help create a better environment for both individuals and society.
                </div>"""

new_cause_effect_2 = """                <h4 style="color: var(--primary-color); margin-top: 25px;">BÀI MẪU 2: DÀN Ý 02 (NGUYÊN NHÂN & ẢNH HƯỞNG)</h4>
                <div class="sample-letter-box">
                    In recent years, <strong>the increase in single-parent families</strong> has become a growing concern in many parts of the world. This issue affects both individuals and society in different ways. <strong>This essay will discuss the main causes of this problem and discuss its possible effects.</strong><br><br>
                    <strong>This issue can be caused by several factors.</strong> One major cause is that <strong>divorce rates are increasing in many countries</strong>. <em>This is because many couples face financial pressure or relationship problems, so they decide to separate.</em> Another contributing factor is that <strong>some young people have unplanned pregnancies</strong>. <em>As a result, some children are raised by only one parent.</em> A further reason is that <strong>society is more accepting of single-parent families nowadays</strong>. <em>Consequently, more people feel comfortable becoming single parents.</em><br><br>
                    <strong>This problem can lead to several negative effects.</strong> One serious impact is that <strong>children in single-parent families may not receive enough parental supervision</strong>. <em>For example, a single parent may spend most of their time working to earn money, so they cannot spend enough time with their children.</em> Another consequence is that <strong>single parents may face financial burdens</strong>. <em>This is because they often have to support the whole family alone.</em> A further problem is that <strong>some children may develop bad behavior</strong>. <em>This is because they may not receive enough guidance from their parents, so they may behave badly at school or do negative things.</em><br><br>
                    In conclusion, <strong>the increase in single-parent families</strong> is caused by several factors and can lead to many negative effects. By understanding the causes and paying more attention to this issue, the situation can be improved in the future. These actions can help create a better environment for both individuals and society.
                </div>"""
content = content.replace(old_cause_effect_2, new_cause_effect_2)

old_cause_effect_3 = """                <h4 style="color: var(--primary-color); margin-top: 25px;">BÀI MẪU 3: DÀN Ý 03 (ẢNH HƯỞNG & GIẢI PHÁP)</h4>
                <div class="sample-letter-box">
                    In recent years, <strong>obesity among young people</strong> has become a growing concern in many parts of the world. This issue affects both individuals and society in different ways. <strong>This essay will discuss the main effects of this problem and suggest possible solutions.</strong><br><br>
                    <strong>This problem can lead to several negative effects.</strong> One serious impact is that <strong>it causes physical health problems</strong>. <em>For instance, overweight young people have a higher risk of heart disease and diabetes.</em> Another consequence is that <strong>it affects mental health negatively</strong>. <em>This is because obese teenagers often feel unconfident about their appearance and may suffer from depression.</em> A further problem is that <strong>it creates a burden on the healthcare system</strong>. <em>This means hospitals need to spend more resources treating obesity-related diseases.</em><br><br>
                    <strong>To solve this problem, several measures can be taken.</strong> One effective solution is to <strong>encourage young people to follow a healthier diet</strong>. <em>The main reason is that eating more vegetables and reducing junk food can help them control their weight and improve their health.</em> Another possible measure is to <strong>promote regular physical exercise at schools</strong>. <em>For example, schools can organize sports activities or encourage students to join exercise clubs after class.</em> Finally, it is important to <strong>educate young people about healthy eating habits</strong>. <em>Therefore, they can make healthier choices in their daily lives.</em><br><br>
                    In conclusion, <strong>obesity among young people</strong> causes several negative effects and requires practical solutions. By taking suitable measures, this problem can be reduced in the future. These solutions can bring positive changes for both individuals and society.
                </div>"""

new_cause_effect_3 = """                <h4 style="color: var(--primary-color); margin-top: 25px;">BÀI MẪU 3: DÀN Ý 03 (ẢNH HƯỞNG & GIẢI PHÁP)</h4>
                <div class="sample-letter-box">
                    In recent years, <strong>cybercrime</strong> has become a growing concern in many parts of the world. This issue affects both individuals and society in different ways. <strong>This essay will discuss the main effects of this problem and suggest possible solutions.</strong><br><br>
                    <strong>This problem can lead to several negative effects.</strong> One serious impact is that <strong>many people may lose money</strong>. <em>This is because cybercriminals can steal personal and financial information, so they can take money from victims’ bank accounts.</em> Another consequence is that <strong>companies may lose important data</strong>. <em>For example, hackers can attack computer systems and damage valuable business information.</em> A further problem is that <strong>many individuals may feel unsafe when using online services</strong>. <em>This is because cybercrime can make the Internet seem dangerous, so some people may avoid online shopping or online banking.</em><br><br>
                    <strong>To solve this problem, several measures can be taken.</strong> One effective solution is to <strong>improve online security systems</strong>. <em>This is because stronger passwords and security software can better protect users from cyber attacks.</em> Another possible measure is to <strong>educate people about online safety</strong>. <em>For example, schools and companies can teach people how to recognize fake messages or dangerous websites.</em> Finally, it is important to <strong>create stricter laws against cybercrime</strong>. <em>As a result, criminals may receive stronger punishments and become less likely to commit online crimes.</em><br><br>
                    In conclusion, <strong>online crime</strong> leads to several negative effects and requires practical solutions. By applying suitable measures and paying more attention to this issue, the situation can be improved in the future. These actions can help create positive changes for both individuals and society.
                </div>"""
content = content.replace(old_cause_effect_3, new_cause_effect_3)

old_cause_effect_4 = """                <h4 style="color: var(--primary-color); margin-top: 25px;">BÀI MẪU 4: DÀN Ý 04 (CHỈ NGUYÊN NHÂN)</h4>
                <div class="sample-letter-box">
                    In recent years, <strong>obesity among young people</strong> has become a growing concern in many parts of the world. Understanding these causes is important to improve the situation in the future. <strong>This essay will discuss the main causes of this problem.</strong><br><br>
                    <strong>This issue can be caused by several factors.</strong> One major cause is that <strong>many young people have unhealthy eating habits</strong>. <em>This is because they often eat fast food and drink sugary beverages, so they consume too much fat and sugar every day.</em> Another contributing factor is that <strong>many young individuals do not exercise regularly</strong>. <em>As a result, they do not burn enough calories and may gain weight easily.</em> A further reason is that <strong>many teenagers lack nutritional knowledge</strong>. <em>Consequently, they may choose unhealthy food and develop poor eating habits.</em><br><br>
                    In conclusion, <strong>obesity among young people</strong> is caused by several factors. By addressing these causes, this problem can be reduced in the future. Therefore, it is important to take suitable actions.
                </div>"""

new_cause_effect_4 = """                <h4 style="color: var(--primary-color); margin-top: 25px;">BÀI MẪU 4: DÀN Ý 04 (CHỈ NGUYÊN NHÂN)</h4>
                <div class="sample-letter-box">
                    In recent years, <strong>young people leaving their companies to start their own businesses</strong> has become a growing trend in many parts of the world. This situation affects both individuals and society in different ways. <strong>This essay will discuss the main causes behind this change.</strong><br><br>
                    One major cause is that <strong>many young people want more freedom and independence at work</strong>. <em>Many employees dislike fixed working hours and strict company rules. In addition, starting a business allows them to make their own decisions and develop their personal ideas. As a result, many young people believe that self-employment can give them a more flexible and satisfying working life.</em><br><br>
                    Another contributing factor is that <strong>many young people want to earn higher incomes</strong>. <em>In some companies, employees may receive low salaries or have limited opportunities for promotion. Moreover, successful business owners can sometimes earn much more money than regular workers. Therefore, many young people believe that starting their own businesses can help them improve their financial situation more quickly.</em><br><br>
                    A further reason is that <strong>the development of technology and social media has made business easier</strong>. <em>Young people can now sell products or advertise services through online platforms with lower costs. For example, many people open online shops or become content creators on social media. Consequently, starting a business has become more convenient and accessible for young people.</em><br><br>
                    In conclusion, <strong>young people choosing self-employment</strong> is caused by several factors that affect both individuals and society. Understanding these causes is important to better understand this situation in the future. With greater attention, suitable support and guidance can also be provided for young entrepreneurs.
                </div>"""
content = content.replace(old_cause_effect_4, new_cause_effect_4)

old_cause_effect_5 = """                <h4 style="color: var(--primary-color); margin-top: 25px;">BÀI MẪU 5: DÀN Ý 05 (CHỈ ẢNH HƯỞNG)</h4>
                <div class="sample-letter-box">
                    In recent years, <strong>obesity among young people</strong> has become a growing concern in many parts of the world. These impacts can affect many areas of life in different ways. <strong>This essay will discuss the main effects of this problem.</strong><br><br>
                    <strong>This problem can lead to several negative effects.</strong> One serious impact is that <strong>it causes physical health problems</strong>. <em>For instance, overweight young people have a higher risk of heart disease and diabetes.</em> Another consequence is that <strong>it affects mental health negatively</strong>. <em>This is because obese teenagers often feel unconfident about their appearance and may suffer from depression.</em> A further consequence is that <strong>it creates a burden on the healthcare system</strong>. <em>This means hospitals need to spend more resources treating obesity-related diseases.</em><br><br>
                    In conclusion, <strong>obesity among young people</strong> can lead to many negative effects. These impacts show that it is a serious issue in modern society. Therefore, it is important to pay more attention to this problem.
                </div>"""

new_cause_effect_5 = """                <h4 style="color: var(--primary-color); margin-top: 25px;">BÀI MẪU 5: DÀN Ý 05 (CHỈ ẢNH HƯỞNG)</h4>
                <div class="sample-letter-box">
                    In recent years, <strong>deforestation</strong> has become a growing concern in many parts of the world. This issue affects both individuals and society in different ways. <strong>This essay will discuss the main effects of this problem.</strong><br><br>
                    One major effect is that <strong>forest destruction causes serious damage to the environment and biodiversity</strong>. <em>In fact, many forests are natural habitats for animals and plants, so cutting down trees destroys their living environment. In addition, some species may gradually disappear because they cannot survive without forests or find enough food and shelter. As a result, ecosystems become weaker and biodiversity is reduced in many areas around the world.</em><br><br>
                    Another serious impact is that <strong>the loss of forests contributes to climate change and natural disasters</strong>. <em>The main reason is that trees help absorb carbon dioxide and control temperatures in the environment. However, when forests are destroyed, more greenhouse gases remain in the atmosphere and global warming becomes more serious. Consequently, many countries may experience floods, droughts, storms, and soil erosion more frequently than before.</em><br><br>
                    A further consequence is that <strong>the removal of forests negatively affects human life</strong>. <em>This is because many local people depend on forests for food, water, medicine, and income in their daily lives. Moreover, environmental damage caused by deforestation can reduce farming productivity and worsen living conditions in these areas. Therefore, many people may face financial difficulties, unemployment, and health problems in the future.</em><br><br>
                    In conclusion, <strong>this environmental issue</strong> leads to several negative effects on both individuals and society. These impacts can affect many areas of life in different ways. Therefore, it is important to pay more attention to this issue in the future.
                </div>"""
content = content.replace(old_cause_effect_5, new_cause_effect_5)

old_cause_effect_6 = """                <h4 style="color: var(--primary-color); margin-top: 25px;">BÀI MẪU 6: DÀN Ý 06 (CHỈ GIẢI PHÁP)</h4>
                <div class="sample-letter-box">
                    In recent years, <strong>obesity among young people</strong> has become increasingly important in modern society. Many people believe that more effective actions are needed in this area. <strong>This essay will suggest some possible solutions to this problem.</strong><br><br>
                    <strong>To solve this problem, several measures can be taken.</strong> One effective solution is to <strong>encourage young people to follow a healthier diet</strong>. <em>The main reason is that eating more vegetables and reducing junk food can help them control their weight and improve their health.</em> Another possible measure is to <strong>promote regular physical exercise at schools</strong>. <em>For example, schools can organize sports activities or encourage students to join exercise clubs after class.</em> A further approach is to <strong>educate young people about healthy eating habits</strong>. <em>Therefore, they can make healthier choices in their daily lives.</em><br><br>
                    In conclusion, <strong>obesity among young people</strong> requires practical solutions. By taking suitable measures, this problem can be reduced in the future. These solutions can bring positive changes for both individuals and society.
                </div>"""

new_cause_effect_6 = """                <h4 style="color: var(--primary-color); margin-top: 25px;">BÀI MẪU 6: DÀN Ý 06 (CHỈ GIẢI PHÁP)</h4>
                <div class="sample-letter-box">
                    In recent years, <strong>promoting language education</strong> has become increasingly important in modern society. Many people believe that more effective actions are needed in this area. <strong>This essay will suggest several practical measures to improve the situation.</strong><br><br>
                    One effective solution is to <strong>improve language teaching methods in schools</strong>. <em>Teachers should use more interactive activities such as games, group discussions, and speaking practice in class instead of focusing only on grammar exercises. In addition, students should be encouraged to use the language in real communication during lessons and daily activities. As a result, students may become more interested in language learning.</em><br><br>
                    Another possible measure is to <strong>increase access to language learning resources</strong>. <em>Schools and governments can provide more books, online materials, videos, and language learning applications for students. Moreover, free or low-cost language courses can help people from low-income families have better opportunities to learn foreign languages. Consequently, more students and adults may be able to study languages more easily.</em><br><br>
                    A further approach is to <strong>create more opportunities for people to practise foreign languages in daily life</strong>. <em>Schools can organize language clubs, cultural exchange programs, or speaking competitions for students on a regular basis. For example, learners can communicate with foreign teachers or international students through these activities and improve their speaking confidence. Therefore, people may become more confident, develop better communication skills, and use foreign languages more naturally in real situations.</em><br><br>
                    In conclusion, <strong>several practical measures</strong> can help improve this situation effectively. These solutions can bring positive changes for both individuals and society. Therefore, it is important to take suitable actions in the future.
                </div>"""
content = content.replace(old_cause_effect_6, new_cause_effect_6)

with open('/Users/nguyetpham/Desktop/WEBSITE/writing-essays-b1level/app.js', 'w') as f:
    f.write(content)

